### ISSUE TITLE
Docs: add a sample readme file (hacktoberfest)

### ISSUE THREAD

**Issue by AhmedGrati** [benmun89/InitialProject#7]
# Description
We should add good documentation for this repository to help hacktoberfest'ers contribute to it. Since I don't have much context about the project, I will add a sample `README.md` file.

**Comment by AhmedGrati** [comment]
@benmun89 Please assign it to me, if you are okay with it! 😁

**Comment by benmun89** [comment]
@AhmedGrati  sure
